required tools

diff --git a/bin/dox b/bin/dox
--- a/bin/dox
+++ b/bin/dox
@@ -52,6 +52,21 @@ function configure_env() {
         export PATH="$(cat "$env_path")$PATH"  # Prepend the new path to the current PATH
     fi
 }
+# Function to check if required tools are installed
+function check_tools() {
+    local tools=("tar" "unzip" "curl" "yq")  # List of required tools
+
+    for tool in "${tools[@]}"; do
+        if ! command -v "$tool" &>/dev/null; then
+            echo "$tool is not installed, which is required for DOX to run" >&2
+            echo "Required tools: (${tools[*]})"
+            exit 1
+        fi
+    done
+}
+
+# Check all tools
+check_tools
 
 # Handle actions based on user input
 case "$action" in
